### ISSUE TITLE
Trigger a command multiple times while keeping the key pressed

### ISSUE THREAD

**Issue by foltri** [iberianpig/fusuma-plugin-keypress#1]
If I want to trigger a command multiple times I have to release and press the key again. Otherwise the gesture triggers a different command that corresponds to the same gesture without the keypress. I was wondering if it's possible to trigger the same command by keeping the key pressed while performing the touchpad gesture multiple times.

```
4:
  left:
    command: 'xdotool key super+Tab'          # 1st command
    keypress:
      LEFTMETA:
        command: 'xdotool key super+Right'    # 2nd command
```
If I do the following:

[ ..... LEFTMETA pressed ..... ]
[ gesture ][ gesture ][ gesture ]

Current behavior is: 2nd command, 1st command, 1st command
Expected behavior is: 2nd command, 2nd command, 2nd command
