### ISSUE TITLE
keypress not working after fusuma 3.3 update

### ISSUE THREAD

**Issue by Armandik** [iberianpig/fusuma-plugin-keypress#10]
I've been using fusuma with keypress and wmctrl to mimic macOS behaviour like it's shown on the fusuma github page on my EndeavourOS KDE install. Ever since I updated to fusuma 3.3.0, keypress (I'm on v0.8) has stopped working and I can't figure out why. My config.yml file loads successfully because all other changes I make work perfectly after logging out and in again.

this is my config file, which was working before the update.
```
swipe:
  4:
    right:
      command: 'xdotool key alt+Right' # History forward
    left:
      command: 'xdotool key alt+Left' # History back
    up:
      #command: 'xdotool key ctrl+t' # Open new tab
      command: 'xdotool key super+F8'
      keypress:
        LEFTSHIFT:
          command: 'xdotool key --clearmodifiers ctrl+shift+t' # Open last closed tab
    down:
      command: 'xdotool key ctrl+w' # Close tab
  3:
    left:
      workspace: 'next' # Switch to next workspace
      keypress:
        LEFTSHIFT: 
          window: 'next' # Move window to next workspace
        LEFTMETA:
          command: 'xdotool key --clearmodifiers super+ctrl+Left' # Move window to left side
    right:
      workspace: 'prev' # Switch to previous workspace
      keypress:
        LEFTSHIFT: 
          window: 'prev' # Move window to previous workspace
        LEFTMETA:
          command: 'xdotool key --clearmodifiers super+ctrl+Right'  # Move window to right side
    up:
      command: 'xdotool key Control_L+F10' # Workspace overview
      keypress:
        LEFTMETA:
          window:
            maximized: 'toggle' # Toggle Maximize/Unmaximize Window
    down:
      command: 'xdotool key Control_L+F12' #minimise all windows
      keypress:
        LEFTMETA:
          window: 'close' # Close window

pinch:
  2:
    in:
      command: 'xdotool keydown ctrl click 4 keyup ctrl' # Zoom in
    out:
      command: 'xdotool keydown ctrl click 5 keyup ctrl' # Zoom out
  4:
    in:
      command: 'xdotool key super+a' # Window overview
    out:
      command: 'xdotool key super+s' # Workspace overview

plugin: 
  inputs:
    libinput_command_input: # options for lib/plugin/inputs/libinput_command_input
      enable-tap: true # click to tap
      enable-dwt: true # disable tap while typing
      show-keycodes: true # https://github.com/iberianpig/fusuma-plugin-keypress#add-show-keycode-option
```

**Comment by iberianpig** [comment]
Could you please paste the output of `fusuma --version`?

**Comment by Armandik** [comment]
```
> fusuma --version
I, [2023-10-31T20:25:49.473349 #2831]  INFO -- : reload config: /home/armando/.config/fusuma/config.yml
I, [2023-10-31T20:25:49.473412 #2831]  INFO -- : ---------------------------------------------
I, [2023-10-31T20:25:49.474791 #2831]  INFO -- : Fusuma: 3.3.0
I, [2023-10-31T20:25:49.476323 #2831]  INFO -- : libinput: 1.24.0
I, [2023-10-31T20:25:49.476364 #2831]  INFO -- : ruby 3.0.6p216
I, [2023-10-31T20:25:49.477744 #2831]  INFO -- : OS: Linux 6.5.9-arch2-1 #1 SMP PREEMPT_DYNAMIC Thu, 26 Oct 2023 00:52:20 +0000
I, [2023-10-31T20:25:49.479273 #2831]  INFO -- : Distribution: EndeavourOS Linux \r (\l)
I, [2023-10-31T20:25:49.483600 #2831]  INFO -- : Desktop session: plasma x11
I, [2023-10-31T20:25:49.483646 #2831]  INFO -- : ---------------------------------------------
I, [2023-10-31T20:25:49.483682 #2831]  INFO -- : Enabled Plugins: 
I, [2023-10-31T20:25:49.483779 #2831]  INFO -- :   Fusuma::Plugin::Buffers::GestureBuffer
I, [2023-10-31T20:25:49.483804 #2831]  INFO -- :   Fusuma::Plugin::Buffers::KeypressBuffer
I, [2023-10-31T20:25:49.483830 #2831]  INFO -- :   Fusuma::Plugin::Buffers::TimerBuffer
I, [2023-10-31T20:25:49.483853 #2831]  INFO -- :   Fusuma::Plugin::Detectors::HoldDetector
I, [2023-10-31T20:25:49.483879 #2831]  INFO -- :   Fusuma::Plugin::Detectors::KeypressDetector
I, [2023-10-31T20:25:49.483899 #2831]  INFO -- :   Fusuma::Plugin::Detectors::PinchDetector
I, [2023-10-31T20:25:49.483922 #2831]  INFO -- :   Fusuma::Plugin::Detectors::RotateDetector
I, [2023-10-31T20:25:49.483946 #2831]  INFO -- :   Fusuma::Plugin::Detectors::SwipeDetector
I, [2023-10-31T20:25:49.483969 #2831]  INFO -- :   Fusuma::Plugin::Events::Records::ContextRecord
I, [2023-10-31T20:25:49.483992 #2831]  INFO -- :   Fusuma::Plugin::Events::Records::GestureRecord
I, [2023-10-31T20:25:49.484015 #2831]  INFO -- :   Fusuma::Plugin::Events::Records::IndexRecord
I, [2023-10-31T20:25:49.484039 #2831]  INFO -- :   Fusuma::Plugin::Events::Records::KeypressRecord
I, [2023-10-31T20:25:49.484063 #2831]  INFO -- :   Fusuma::Plugin::Events::Records::TextRecord
I, [2023-10-31T20:25:49.484085 #2831]  INFO -- :   Fusuma::Plugin::Executors::CommandExecutor
I, [2023-10-31T20:25:49.484106 #2831]  INFO -- :   Fusuma::Plugin::Executors::WmctrlExecutor
I, [2023-10-31T20:25:49.484128 #2831]  INFO -- :   Fusuma::Plugin::Filters::KeypressFilter
I, [2023-10-31T20:25:49.484150 #2831]  INFO -- :   Fusuma::Plugin::Filters::LibinputDeviceFilter
I, [2023-10-31T20:25:49.484171 #2831]  INFO -- :   Fusuma::Plugin::Inputs::LibinputCommandInput
I, [2023-10-31T20:25:49.484192 #2831]  INFO -- :   Fusuma::Plugin::Inputs::TimerInput
I, [2023-10-31T20:25:49.484236 #2831]  INFO -- :   Fusuma::Plugin::Parsers::KeypressParser
I, [2023-10-31T20:25:49.484260 #2831]  INFO -- :   Fusuma::Plugin::Parsers::LibinputGestureParser
I, [2023-10-31T20:25:49.484283 #2831]  INFO -- : ---------------------------------------------
```

**Comment by iberianpig** [comment]
I will create an environment to reproduce the bug and confirm it.



- Gemfile
```ruby
# frozen_string_literal: true

source 'https://rubygems.org'

gem 'fusuma', '3.3'

# plugins
gem 'fusuma-plugin-keypress'
gem 'fusuma-plugin-wmctrl'

# for debug
gem 'debug'

# profiling
gem 'rblineprof'
gem 'rblineprof-report'

```


- Dump configuration

```yaml
iberianpig@iberianpig-XPS-13-9310:~/fusuma_dev/v3_3$ be fusuma --config issue_keypress_10.yml --show-config
I, [2023-11-01T10:09:32.678480 #549762]  INFO -- : reload config: /home/iberianpig/fusuma_dev/v3_3/issue_keypress_10.yml
I, [2023-11-01T10:09:32.678568 #549762]  INFO -- : ---------------------------------------------
I, [2023-11-01T10:09:32.679452 #549762]  INFO -- : Fusuma: 3.3.0
I, [2023-11-01T10:09:32.680427 #549762]  INFO -- : libinput: 1.20.0
I, [2023-11-01T10:09:32.680458 #549762]  INFO -- : ruby 3.0.4p208
I, [2023-11-01T10:09:32.681207 #549762]  INFO -- : OS: Linux 5.14.0-1034-oem #37-Ubuntu SMP Tue Apr 19 14:13:20 UTC 2022
I, [2023-11-01T10:09:32.681903 #549762]  INFO -- : Distribution: Ubuntu 22.04.2 LTS \n \l
I, [2023-11-01T10:09:32.682511 #549762]  INFO -- : Desktop session: ubuntu-xorg x11
I, [2023-11-01T10:09:32.682538 #549762]  INFO -- : ---------------------------------------------
I, [2023-11-01T10:09:32.682551 #549762]  INFO -- : Enabled Plugins:
I, [2023-11-01T10:09:32.682637 #549762]  INFO -- :   Fusuma::Plugin::Buffers::GestureBuffer
I, [2023-11-01T10:09:32.682653 #549762]  INFO -- :   Fusuma::Plugin::Buffers::KeypressBuffer
I, [2023-11-01T10:09:32.682660 #549762]  INFO -- :   Fusuma::Plugin::Buffers::TimerBuffer
I, [2023-11-01T10:09:32.682668 #549762]  INFO -- :   Fusuma::Plugin::Detectors::HoldDetector
I, [2023-11-01T10:09:32.682675 #549762]  INFO -- :   Fusuma::Plugin::Detectors::KeypressDetector
I, [2023-11-01T10:09:32.682682 #549762]  INFO -- :   Fusuma::Plugin::Detectors::PinchDetector
I, [2023-11-01T10:09:32.682689 #549762]  INFO -- :   Fusuma::Plugin::Detectors::RotateDetector
I, [2023-11-01T10:09:32.682697 #549762]  INFO -- :   Fusuma::Plugin::Detectors::SwipeDetector
I, [2023-11-01T10:09:32.682705 #549762]  INFO -- :   Fusuma::Plugin::Events::Records::ContextRecord
I, [2023-11-01T10:09:32.682713 #549762]  INFO -- :   Fusuma::Plugin::Events::Records::GestureRecord
I, [2023-11-01T10:09:32.682721 #549762]  INFO -- :   Fusuma::Plugin::Events::Records::IndexRecord
I, [2023-11-01T10:09:32.682728 #549762]  INFO -- :   Fusuma::Plugin::Events::Records::KeypressRecord
I, [2023-11-01T10:09:32.682735 #549762]  INFO -- :   Fusuma::Plugin::Events::Records::TextRecord
I, [2023-11-01T10:09:32.682742 #549762]  INFO -- :   Fusuma::Plugin::Executors::CommandExecutor
I, [2023-11-01T10:09:32.682749 #549762]  INFO -- :   Fusuma::Plugin::Executors::WmctrlExecutor
I, [2023-11-01T10:09:32.682756 #549762]  INFO -- :   Fusuma::Plugin::Filters::KeypressFilter
I, [2023-11-01T10:09:32.682764 #549762]  INFO -- :   Fusuma::Plugin::Filters::LibinputDeviceFilter
I, [2023-11-01T10:09:32.682771 #549762]  INFO -- :   Fusuma::Plugin::Inputs::LibinputCommandInput
I, [2023-11-01T10:09:32.682779 #549762]  INFO -- :   Fusuma::Plugin::Inputs::TimerInput
I, [2023-11-01T10:09:32.682786 #549762]  INFO -- :   Fusuma::Plugin::Parsers::KeypressParser
I, [2023-11-01T10:09:32.682793 #549762]  INFO -- :   Fusuma::Plugin::Parsers::LibinputGestureParser
I, [2023-11-01T10:09:32.682801 #549762]  INFO -- : ---------------------------------------------
---
swipe:
  '4':
    right:
      command: xdotool key alt+Right
    left:
      command: xdotool key alt+Left
    up:
      command: xdotool key super+F8
      keypress:
        LEFTSHIFT:
          command: xdotool key --clearmodifiers ctrl+shift+t
    down:
      command: xdotool key ctrl+w
  '3':
    left:
      workspace: next
      keypress:
        LEFTSHIFT:
          window: next
        LEFTMETA:
          command: xdotool key --clearmodifiers super+ctrl+Left
    right:
      workspace: prev
      keypress:
        LEFTSHIFT:
          window: prev
        LEFTMETA:
          command: xdotool key --clearmodifiers super+ctrl+Right
    up:
      command: xdotool key Control_L+F10
      keypress:
        LEFTMETA:
          window:
            maximized: toggle
    down:
      command: xdotool key Control_L+F12
      keypress:
        LEFTMETA:
          window: close
pinch:
  '2':
    in:
      command: xdotool keydown ctrl click 4 keyup ctrl
    out:
      command: xdotool keydown ctrl click 5 keyup ctrl
  '4':
    in:
      command: xdotool key super+a
    out:
      command: xdotool key super+s
plugin:
  inputs:
    libinput_command_input:
      enable-tap: true
      enable-dwt: true
      show-keycodes: true
---
context:
  plugin_defaults: libinput_command_input
plugin:
  inputs:
    libinput_command_input:
---
context:
  plugin_defaults: wmctrl_executor
plugin:
  executors:
    wmctrl_executor:
      wrap-navigation: false
      matrix-col-size:
```



I found that some settings were not working. 
There seems to be a bug in fusuma-plugin-wmctl.

```yaml
swipe:
  4:
    up:
      command: 'xdotool key super+F8' # <- works
      keypress:
        LEFTSHIFT:
          command: 'xdotool key --clearmodifiers ctrl+shift+t' # Open last closed tab # <- works
  3:
    up:
      command: 'xdotool key Control_L+F10' # Workspace overview # <- works
      keypress:
        LEFTMETA:
          window:
            maximized: 'toggle' # Toggle Maximize/Unmaximize Window # <- doesn't work
```
