### ISSUE TITLE
Only 'LEFTMETA' keycode works on KDE Plasma

### ISSUE THREAD

**Issue by emvaized** [iberianpig/fusuma-plugin-keypress#2]
Trying LEFTCTRL or LEFTSHIFT gives no result -- only main swipe action is triggered on holding key.
Trying LEFTMETA triggers 'keycode' action as intended, but application menu keeps opening and popping.

Here's my full `config.yml`:
```
swipe:
  3:
    left:
      sendkey: "LEFTALT+RIGHT" # History forward 
    right:
      sendkey: "LEFTALT+LEFT" # History back
    up:
      sendkey: "LEFTMETA+PAGEUP" # Maximize window
    down:
      sendkey: "LEFTMETA+PAGEDOWN" # Minimize window
  4:
    left:
      sendkey: "LEFTCTRL+F2" # Switch to second workspace
      threshold: 0.15
      interval: 0.15
      keypress:
        LEFTCTRL:
            sendkey: "LEFTALT+F9" # Volume down       <-- This one is not triggered
    right:
      sendkey: "LEFTCTRL+F1" # Swich to first workspace
      threshold: 0.1
      interval: 0.1
      keypress:
        LEFTCTRL
            sendkey: "LEFTALT+F10" # Volume up           <-- As well as this one
    up:
      sendkey: "LEFTALT+TAB" # Switch to previous window
      keypress:
        LEFTSHIFT:
            command: 'xdotool key --clearmodifiers XF86AudioRaiseVolume'   # <-- This doesn't work too
    down:   
      sendkey: "LEFTALT+F4" # Switch to previous workspace
      keypress:
        LEFTMETA:
            command: 'xdotool key --clearmodifiers XF86AudioLowerVolume' # <-- And this one works    
pinch:
    3:
        in:
            command: 'xdotool key super+d' 
        out:
            command: 'xdotool key ctrl+F9' # Window overview

hold:
  3:
    sendkey: "LEFTCTRL+B" #Open clipboard manager
  4:
    sendkey: "LEFTCTRL+T" # Open new tab
            
threshold:
  swipe: 0.45

interval:
  swipe: 0.45
  
plugin: 
  inputs:
    libinput_command_input:
      show-keycode: true
      enable-tap: true # click to tap
      enable-dwt: true # disable tap while typing
      verbose: true
```
