### ISSUE TITLE
Feature/Typing Detector for disable touchpad while typing

### ISSUE THREAD

**Issue by iberianpig** [iberianpig/fusuma-plugin-keypress#6]
We are using xkeysnail as a key remapper.
However, when xkeysnail is used, libinput does not enable disable-while-typing.

Currently, only modifier keys can be detected, however, I need to add functionality so that events are triggered when keys other than modifier keys are pressed. In addition, it will be triggered by only typing keys without any touchpad gestures (swipe/pinch).

example: Disabling the touchpad for 1 second

```yaml
typing:
  command: disable_touchpad_for_1second.sh
  interval: 1
```
